import {i18n} from "@/lang";

const phoneAreaCode = [
    {
        'short': 'AD',
        'name': i18n.t('安道尔共和国'),
        'en': 'Andorra',
        'tel': '376'
    }, {
        'short': 'AE',
        'name': i18n.t('阿拉伯联合酋长国'),
        'en': 'UnitedArabEmirates',
        'tel': '971'
    }, {
        'short': 'AF',
        'name': i18n.t('阿富汗'),
        'en': 'Afghanistan',
        'tel': '93'
    }, {
        'short': 'AG',
        'name': i18n.t('安提瓜和巴布达'),
        'en': 'AntiguaandBarbuda',
        'tel': '1268'
    }, {
        'short': 'AI',
        'name': i18n.t('安圭拉岛'),
        'en': 'Anguilla',
        'tel': '1264'
    }, {
        'short': 'AL',
        'name': i18n.t('阿尔巴尼亚'),
        'en': 'Albania',
        'tel': '355'
    }, {
        'short': 'AM',
        'name': i18n.t('亚美尼亚'),
        'en': 'Armenia',
        'tel': '374'
    }, {
        'short': '',
        'name': i18n.t('阿森松'),
        'en': 'Ascension',
        'tel': '247'
    }, {
        'short': 'AO',
        'name': i18n.t('安哥拉'),
        'en': 'Angola',
        'tel': '244'
    }, {
        'short': 'AR',
        'name': i18n.t('阿根廷'),
        'en': 'Argentina',
        'tel': '54'
    }, {
        'short': 'AT',
        'name': i18n.t('奥地利'),
        'en': 'Austria',
        'tel': '43'
    }, {
        'short': 'AU',
        'name': i18n.t('澳大利亚'),
        'en': 'Australia',
        'tel': '61'
    }, {
        'short': 'AZ',
        'name': i18n.t('阿塞拜疆'),
        'en': 'Azerbaijan',
        'tel': '994'
    }, {
        'short': 'BB',
        'name': i18n.t('巴巴多斯'),
        'en': 'Barbados',
        'tel': '1246'
    }, {
        'short': 'BD',
        'name': i18n.t('孟加拉国'),
        'en': 'Bangladesh',
        'tel': '880'
    }, {
        'short': 'BE',
        'name': i18n.t('比利时'),
        'en': 'Belgium',
        'tel': '32'
    }, {
        'short': 'BF',
        'name': i18n.t('布基纳法索'),
        'en': 'Burkina-faso',
        'tel': '226'
    }, {
        'short': 'BG',
        'name': i18n.t('保加利亚'),
        'en': 'Bulgaria',
        'tel': '359'
    }, {
        'short': 'BH',
        'name': i18n.t('巴林'),
        'en': 'Bahrain',
        'tel': '973'
    }, {
        'short': 'BI',
        'name': i18n.t('布隆迪'),
        'en': 'Burundi',
        'tel': '257'
    }, {
        'short': 'BJ',
        'name': i18n.t('贝宁'),
        'en': 'Benin',
        'tel': '229'
    }, {
        'short': 'BL',
        'name': i18n.t('巴勒斯坦'),
        'en': 'Palestine',
        'tel': '970'
    }, {
        'short': 'BM',
        'name': i18n.t('百慕大群岛'),
        'en': 'BermudaIs.',
        'tel': '1441'
    }, {
        'short': 'BN',
        'name': i18n.t('文莱'),
        'en': 'Brunei',
        'tel': '673'
    }, {
        'short': 'BO',
        'name': i18n.t('玻利维亚'),
        'en': 'Bolivia',
        'tel': '591'
    }, {
        'short': 'BR',
        'name': i18n.t('巴西'),
        'en': 'Brazil',
        'tel': '55'
    }, {
        'short': 'BS',
        'name': i18n.t('巴哈马'),
        'en': 'Bahamas',
        'tel': '1242'
    }, {
        'short': 'BW',
        'name': i18n.t('博茨瓦纳'),
        'en': 'Botswana',
        'tel': '267'
    }, {
        'short': 'BY',
        'name': i18n.t('白俄罗斯'),
        'en': 'Belarus',
        'tel': '375'
    }, {
        'short': 'BZ',
        'name': i18n.t('伯利兹'),
        'en': 'Belize',
        'tel': '501'
    }, {
        'short': 'CA',
        'name': i18n.t('加拿大'),
        'en': 'Canada',
        'tel': '1'
    }, {
        'short': '',
        'name': i18n.t('开曼群岛'),
        'en': 'CaymanIs.',
        'tel': '1345'
    }, {
        'short': 'CF',
        'name': i18n.t('中非共和国'),
        'en': 'CentralAfricanRepublic',
        'tel': '236'
    }, {
        'short': 'CG',
        'name': i18n.t('刚果'),
        'en': 'Congo',
        'tel': '242'
    }, {
        'short': 'CH',
        'name': i18n.t('瑞士'),
        'en': 'Switzerland',
        'tel': '41'
    }, {
        'short': 'CK',
        'name': i18n.t('库克群岛'),
        'en': 'CookIs.',
        'tel': '682'
    }, {
        'short': 'CL',
        'name': i18n.t('智利'),
        'en': 'Chile',
        'tel': '56'
    }, {
        'short': 'CM',
        'name': i18n.t('喀麦隆'),
        'en': 'Cameroon',
        'tel': '237'
    }, {
        'short': 'CN',
        'name': i18n.t('中国'),
        'en': 'China',
        'tel': '86'
    }, {
        'short': 'CO',
        'name': i18n.t('哥伦比亚'),
        'en': 'Colombia',
        'tel': '57'
    }, {
        'short': 'CR',
        'name': i18n.t('哥斯达黎加'),
        'en': 'CostaRica',
        'tel': '506'
    }, {
        'short': 'CS',
        'name': i18n.t('捷克'),
        'en': 'Czech',
        'tel': '420'
    }, {
        'short': 'CU',
        'name': i18n.t('古巴'),
        'en': 'Cuba',
        'tel': '53'
    }, {
        'short': 'CY',
        'name': i18n.t('塞浦路斯'),
        'en': 'Cyprus',
        'tel': '357'
    }, {
        'short': 'CZ',
        'name': i18n.t('捷克'),
        'en': 'CzechRepublic',
        'tel': '420'
    }, {
        'short': 'DE',
        'name': i18n.t('德国'),
        'en': 'Germany',
        'tel': '49'
    }, {
        'short': 'DJ',
        'name': i18n.t('吉布提'),
        'en': 'Djibouti',
        'tel': '253'
    }, {
        'short': 'DK',
        'name': i18n.t('丹麦'),
        'en': 'Denmark',
        'tel': '45'
    }, {
        'short': 'DO',
        'name': i18n.t('多米尼加共和国'),
        'en': 'DominicaRep.',
        'tel': '1890'
    }, {
        'short': 'DZ',
        'name': i18n.t('阿尔及利亚'),
        'en': 'Algeria',
        'tel': '213'
    }, {
        'short': 'EC',
        'name': i18n.t('厄瓜多尔'),
        'en': 'Ecuador',
        'tel': '593'
    }, {
        'short': 'EE',
        'name': i18n.t('爱沙尼亚'),
        'en': 'Estonia',
        'tel': '372'
    }, {
        'short': 'EG',
        'name': i18n.t('埃及'),
        'en': 'Egypt',
        'tel': '20'
    }, {
        'short': 'ES',
        'name': i18n.t('西班牙'),
        'en': 'Spain',
        'tel': '34'
    }, {
        'short': 'ET',
        'name': i18n.t('埃塞俄比亚'),
        'en': 'Ethiopia',
        'tel': '251'
    }, {
        'short': 'FI',
        'name': i18n.t('芬兰'),
        'en': 'Finland',
        'tel': '358'
    }, {
        'short': 'FJ',
        'name': i18n.t('斐济'),
        'en': 'Fiji',
        'tel': '679'
    }, {
        'short': 'FR',
        'name': i18n.t('法国'),
        'en': 'France',
        'tel': '33'
    }, {
        'short': 'GA',
        'name': i18n.t('加蓬'),
        'en': 'Gabon',
        'tel': '241'
    }, {
        'short': 'GB',
        'name': i18n.t('英国'),
        'en': 'UnitedKiongdom',
        'tel': '44'
    }, {
        'short': 'GD',
        'name': i18n.t('格林纳达'),
        'en': 'Grenada',
        'tel': '1809'
    }, {
        'short': 'GE',
        'name': i18n.t('格鲁吉亚'),
        'en': 'Georgia',
        'tel': '995'
    }, {
        'short': 'GF',
        'name': i18n.t('法属圭亚那'),
        'en': 'FrenchGuiana',
        'tel': '594'
    }, {
        'short': 'GH',
        'name': i18n.t('加纳'),
        'en': 'Ghana',
        'tel': '233'
    }, {
        'short': 'GI',
        'name': i18n.t('直布罗陀'),
        'en': 'Gibraltar',
        'tel': '350'
    }, {
        'short': 'GM',
        'name': i18n.t('冈比亚'),
        'en': 'Gambia',
        'tel': '220'
    }, {
        'short': 'GN',
        'name': i18n.t('几内亚'),
        'en': 'Guinea',
        'tel': '224'
    }, {
        'short': 'GR',
        'name': i18n.t('希腊'),
        'en': 'Greece',
        'tel': '30'
    }, {
        'short': 'GT',
        'name': i18n.t('危地马拉'),
        'en': 'Guatemala',
        'tel': '502'
    }, {
        'short': 'GU',
        'name': i18n.t('关岛'),
        'en': 'Guam',
        'tel': '1671'
    }, {
        'short': 'GY',
        'name': i18n.t('圭亚那'),
        'en': 'Guyana',
        'tel': '592'
    }, {
        'short': 'HK',
        'name': i18n.t('香港特别行政区'),
        'en': 'Hongkong',
        'tel': '852'
    }, {
        'short': 'HN',
        'name': i18n.t('洪都拉斯'),
        'en': 'Honduras',
        'tel': '504'
    }, {
        'short': 'HT',
        'name': i18n.t('海地'),
        'en': 'Haiti',
        'tel': '509'
    }, {
        'short': 'HU',
        'name': i18n.t('匈牙利'),
        'en': 'Hungary',
        'tel': '36'
    }, {
        'short': 'ID',
        'name': i18n.t('印度尼西亚'),
        'en': 'Indonesia',
        'tel': '62'
    }, {
        'short': 'IE',
        'name': i18n.t('爱尔兰'),
        'en': 'Ireland',
        'tel': '353'
    }, {
        'short': 'IL',
        'name': i18n.t('以色列'),
        'en': 'Israel',
        'tel': '972'
    }, {
        'short': 'IN',
        'name': i18n.t('印度'),
        'en': 'India',
        'tel': '91'
    }, {
        'short': 'IQ',
        'name': i18n.t('伊拉克'),
        'en': 'Iraq',
        'tel': '964'
    }, {
        'short': 'IR',
        'name': i18n.t('伊朗'),
        'en': 'Iran',
        'tel': '98'
    }, {
        'short': 'IS',
        'name': i18n.t('冰岛'),
        'en': 'Iceland',
        'tel': '354'
    }, {
        'short': 'IT',
        'name': i18n.t('意大利'),
        'en': 'Italy',
        'tel': '39'
    }, {
        'short': '',
        'name': i18n.t('科特迪瓦'),
        'en': 'IvoryCoast',
        'tel': '225'
    }, {
        'short': 'JM',
        'name': i18n.t('牙买加'),
        'en': 'Jamaica',
        'tel': '1876'
    }, {
        'short': 'JO',
        'name': i18n.t('约旦'),
        'en': 'Jordan',
        'tel': '962'
    }, {
        'short': 'JP',
        'name': i18n.t('日本'),
        'en': 'Japan',
        'tel': '81'
    }, {
        'short': 'KE',
        'name': i18n.t('肯尼亚'),
        'en': 'Kenya',
        'tel': '254'
    }, {
        'short': 'KG',
        'name': i18n.t('吉尔吉斯坦'),
        'en': 'Kyrgyzstan',
        'tel': '331'
    }, {
        'short': 'KH',
        'name': i18n.t('柬埔寨'),
        'en': 'Kampuchea(Cambodia)',
        'tel': '855'
    }, {
        'short': 'KP',
        'name': i18n.t('朝鲜'),
        'en': 'NorthKorea',
        'tel': '850'
    }, {
        'short': 'KR',
        'name': i18n.t('韩国'),
        'en': 'Korea',
        'tel': '82'
    }, {
        'short': 'KT',
        'name': i18n.t('科特迪瓦共和国'),
        'en': 'RepublicofIvoryCoast',
        'tel': '225'
    }, {
        'short': 'KW',
        'name': i18n.t('科威特'),
        'en': 'Kuwait',
        'tel': '965'
    }, {
        'short': 'KZ',
        'name': i18n.t('哈萨克斯坦'),
        'en': 'Kazakstan',
        'tel': '327'
    }, {
        'short': 'LA',
        'name': i18n.t('老挝'),
        'en': 'Laos',
        'tel': '856'
    }, {
        'short': 'LB',
        'name': i18n.t('黎巴嫩'),
        'en': 'Lebanon',
        'tel': '961'
    }, {
        'short': 'LC',
        'name': i18n.t('圣卢西亚'),
        'en': 'St.Lucia',
        'tel': '1758'
    }, {
        'short': 'LI',
        'name': i18n.t('列支敦士登'),
        'en': 'Liechtenstein',
        'tel': '423'
    }, {
        'short': 'LK',
        'name': i18n.t('斯里兰卡'),
        'en': 'SriLanka',
        'tel': '94'
    }, {
        'short': 'LR',
        'name': i18n.t('利比里亚'),
        'en': 'Liberia',
        'tel': '231'
    }, {
        'short': 'LS',
        'name': i18n.t('莱索托'),
        'en': 'Lesotho',
        'tel': '266'
    }, {
        'short': 'LT',
        'name': i18n.t('立陶宛'),
        'en': 'Lithuania',
        'tel': '370'
    }, {
        'short': 'LU',
        'name': i18n.t('卢森堡'),
        'en': 'Luxembourg',
        'tel': '352'
    }, {
        'short': 'LV',
        'name': i18n.t('拉脱维亚'),
        'en': 'Latvia',
        'tel': '371'
    }, {
        'short': 'LY',
        'name': i18n.t('利比亚'),
        'en': 'Libya',
        'tel': '218'
    }, {
        'short': 'MA',
        'name': i18n.t('摩洛哥'),
        'en': 'Morocco',
        'tel': '212'
    }, {
        'short': 'MC',
        'name': i18n.t('摩纳哥'),
        'en': 'Monaco',
        'tel': '377'
    }, {
        'short': 'MD',
        'name': i18n.t('摩尔多瓦'),
        'en': 'Moldova,Republicof',
        'tel': '373'
    }, {
        'short': 'MG',
        'name': i18n.t('马达加斯加'),
        'en': 'Madagascar',
        'tel': '261'
    }, {
        'short': 'ML',
        'name': i18n.t('马里'),
        'en': 'Mali',
        'tel': '223'
    }, {
        'short': 'MM',
        'name': i18n.t('缅甸'),
        'en': 'Burma',
        'tel': '95'
    }, {
        'short': 'MN',
        'name': i18n.t('蒙古'),
        'en': 'Mongolia',
        'tel': '976'
    }, {
        'short': 'MO',
        'name': i18n.t('澳门'),
        'en': 'Macao',
        'tel': '853'
    }, {
        'short': 'MS',
        'name': i18n.t('蒙特塞拉特岛'),
        'en': 'MontserratIs',
        'tel': '1664'
    }, {
        'short': 'MT',
        'name': i18n.t('马耳他'),
        'en': 'Malta',
        'tel': '356'
    }, {
        'short': '',
        'name': i18n.t('马里亚那群岛'),
        'en': 'MarianaIs',
        'tel': '1670'
    }, {
        'short': '',
        'name': i18n.t('马提尼克'),
        'en': 'Martinique',
        'tel': '596'
    }, {
        'short': 'MU',
        'name': i18n.t('毛里求斯'),
        'en': 'Mauritius',
        'tel': '230'
    }, {
        'short': 'MV',
        'name': i18n.t('马尔代夫'),
        'en': 'Maldives',
        'tel': '960'
    }, {
        'short': 'MW',
        'name': i18n.t('马拉维'),
        'en': 'Malawi',
        'tel': '265'
    }, {
        'short': 'MX',
        'name': i18n.t('墨西哥'),
        'en': 'Mexico',
        'tel': '52'
    }, {
        'short': 'MY',
        'name': i18n.t('马来西亚'),
        'en': 'Malaysia',
        'tel': '60'
    }, {
        'short': 'MZ',
        'name': i18n.t('莫桑比克'),
        'en': 'Mozambique',
        'tel': '258'
    }, {
        'short': 'NA',
        'name': i18n.t('纳米比亚'),
        'en': 'Namibia',
        'tel': '264'
    }, {
        'short': 'NE',
        'name': i18n.t('尼日尔'),
        'en': 'Niger',
        'tel': '977'
    }, {
        'short': 'NG',
        'name': i18n.t('尼日利亚'),
        'en': 'Nigeria',
        'tel': '234'
    }, {
        'short': 'NI',
        'name': i18n.t('尼加拉瓜'),
        'en': 'Nicaragua',
        'tel': '505'
    }, {
        'short': 'NL',
        'name': i18n.t('荷兰'),
        'en': 'Netherlands',
        'tel': '31'
    }, {
        'short': 'NO',
        'name': i18n.t('挪威'),
        'en': 'Norway',
        'tel': '47'
    }, {
        'short': 'NP',
        'name': i18n.t('尼泊尔'),
        'en': 'Nepal',
        'tel': '977'
    }, {
        'short': '',
        'name': i18n.t('荷属安的列斯'),
        'en': 'NetheriandsAntilles',
        'tel': '599'
    }, {
        'short': 'NR',
        'name': i18n.t('瑙鲁'),
        'en': 'Nauru',
        'tel': '674'
    }, {
        'short': 'NZ',
        'name': i18n.t('新西兰'),
        'en': 'NewZealand',
        'tel': '64'
    }, {
        'short': 'OM',
        'name': i18n.t('阿曼'),
        'en': 'Oman',
        'tel': '968'
    }, {
        'short': 'PA',
        'name': i18n.t('巴拿马'),
        'en': 'Panama',
        'tel': '507'
    }, {
        'short': 'PE',
        'name': i18n.t('秘鲁'),
        'en': 'Peru',
        'tel': '51'
    }, {
        'short': 'PF',
        'name': i18n.t('法属玻利尼西亚'),
        'en': 'FrenchPolynesia',
        'tel': '689'
    }, {
        'short': 'PG',
        'name': i18n.t('巴布亚新几内亚'),
        'en': 'PapuaNewCuinea',
        'tel': '675'
    }, {
        'short': 'PH',
        'name': i18n.t('菲律宾'),
        'en': 'Philippines',
        'tel': '63'
    }, {
        'short': 'PK',
        'name': i18n.t('巴基斯坦'),
        'en': 'Pakistan',
        'tel': '92'
    }, {
        'short': 'PL',
        'name': i18n.t('波兰'),
        'en': 'Poland',
        'tel': '48'
    }, {
        'short': 'PR',
        'name': i18n.t('波多黎各'),
        'en': 'PuertoRico',
        'tel': '1787'
    }, {
        'short': 'PT',
        'name': i18n.t('葡萄牙'),
        'en': 'Portugal',
        'tel': '351'
    }, {
        'short': 'PY',
        'name': i18n.t('巴拉圭'),
        'en': 'Paraguay',
        'tel': '595'
    }, {
        'short': 'QA',
        'name': i18n.t('卡塔尔'),
        'en': 'Qatar',
        'tel': '974'
    }, {
        'short': '',
        'name': i18n.t('留尼旺'),
        'en': 'Reunion',
        'tel': '262'
    }, {
        'short': 'RO',
        'name': i18n.t('罗马尼亚'),
        'en': 'Romania',
        'tel': '40'
    }, {
        'short': 'RU',
        'name': i18n.t('俄罗斯'),
        'en': 'Russia',
        'tel': '7'
    }, {
        'short': 'SA',
        'name': i18n.t('沙特阿拉伯'),
        'en': 'SaudiArabia',
        'tel': '966'
    }, {
        'short': 'SB',
        'name': i18n.t('所罗门群岛'),
        'en': 'SolomonIs',
        'tel': '677'
    }, {
        'short': 'SC',
        'name': i18n.t('塞舌尔'),
        'en': 'Seychelles',
        'tel': '248'
    }, {
        'short': 'SD',
        'name': i18n.t('苏丹'),
        'en': 'Sudan',
        'tel': '249'
    }, {
        'short': 'SE',
        'name': i18n.t('瑞典'),
        'en': 'Sweden',
        'tel': '46'
    }, {
        'short': 'SG',
        'name': i18n.t('新加坡'),
        'en': 'Singapore',
        'tel': '65'
    }, {
        'short': 'SI',
        'name': i18n.t('斯洛文尼亚'),
        'en': 'Slovenia',
        'tel': '386'
    }, {
        'short': 'SK',
        'name': i18n.t('斯洛伐克'),
        'en': 'Slovakia',
        'tel': '421'
    }, {
        'short': 'SL',
        'name': i18n.t('塞拉利昂'),
        'en': 'SierraLeone',
        'tel': '232'
    }, {
        'short': 'SM',
        'name': i18n.t('圣马力诺'),
        'en': 'SanMarino',
        'tel': '378'
    }, {
        'short': '',
        'name': '东萨摩亚(美)',
        'en': 'SamoaEastern',
        'tel': '684'
    }, {
        'short': '',
        'name': i18n.t('西萨摩亚'),
        'en': 'SanMarino',
        'tel': '685'
    }, {
        'short': 'SN',
        'name': i18n.t('塞内加尔'),
        'en': 'Senegal',
        'tel': '221'
    }, {
        'short': 'SO',
        'name': i18n.t('索马里'),
        'en': 'Somali',
        'tel': '252'
    }, {
        'short': 'SR',
        'name': i18n.t('苏里南'),
        'en': 'Suriname',
        'tel': '597'
    }, {
        'short': 'ST',
        'name': i18n.t('圣多美和普林西比'),
        'en': 'SaoTomeandPrincipe',
        'tel': '239'
    }, {
        'short': 'SV',
        'name': i18n.t('萨尔瓦多'),
        'en': 'EISalvador',
        'tel': '503'
    }, {
        'short': 'SY',
        'name': i18n.t('叙利亚'),
        'en': 'Syria',
        'tel': '963'
    }, {
        'short': 'SZ',
        'name': i18n.t('斯威士兰'),
        'en': 'Swaziland',
        'tel': '268'
    }, {
        'short': 'TD',
        'name': i18n.t('乍得'),
        'en': 'Chad',
        'tel': '235'
    }, {
        'short': 'TG',
        'name': i18n.t('多哥'),
        'en': 'Togo',
        'tel': '228'
    }, {
        'short': 'TH',
        'name': i18n.t('泰国'),
        'en': 'Thailand',
        'tel': '66'
    }, {
        'short': 'TJ',
        'name': i18n.t('塔吉克斯坦'),
        'en': 'Tajikstan',
        'tel': '992'
    }, {
        'short': 'TM',
        'name': i18n.t('土库曼斯坦'),
        'en': 'Turkmenistan',
        'tel': '993'
    }, {
        'short': 'TN',
        'name': i18n.t('突尼斯'),
        'en': 'Tunisia',
        'tel': '216'
    }, {
        'short': 'TO',
        'name': i18n.t('汤加'),
        'en': 'Tonga',
        'tel': '676'
    }, {
        'short': 'TR',
        'name': i18n.t('土耳其'),
        'en': 'Turkey',
        'tel': '90'
    }, {
        'short': 'TT',
        'name': i18n.t('特立尼达和多巴哥'),
        'en': 'TrinidadandTobago',
        'tel': '1809'
    }, {
        'short': 'TW',
        'name': i18n.t('台湾省'),
        'en': 'Taiwan',
        'tel': '886'
    }, {
        'short': 'TZ',
        'name': i18n.t('坦桑尼亚'),
        'en': 'Tanzania',
        'tel': '255'
    }, {
        'short': 'UA',
        'name': i18n.t('乌克兰'),
        'en': 'Ukraine',
        'tel': '380'
    }, {
        'short': 'UG',
        'name': i18n.t('乌干达'),
        'en': 'Uganda',
        'tel': '256'
    }, {
        'short': 'US',
        'name': i18n.t('美国'),
        'en': 'UnitedStatesofAmerica',
        'tel': '1'
    }, {
        'short': 'UY',
        'name': i18n.t('乌拉圭'),
        'en': 'Uruguay',
        'tel': '598'
    }, {
        'short': 'UZ',
        'name': i18n.t('乌兹别克斯坦'),
        'en': 'Uzbekistan',
        'tel': '233'
    }, {
        'short': 'VC',
        'name': i18n.t('圣文森特岛'),
        'en': 'SaintVincent',
        'tel': '1784'
    }, {
        'short': 'VE',
        'name': i18n.t('委内瑞拉'),
        'en': 'Venezuela',
        'tel': '58'
    }, {
        'short': 'VN',
        'name': i18n.t('越南'),
        'en': 'Vietnam',
        'tel': '84'
    }, {
        'short': 'YE',
        'name': i18n.t('也门'),
        'en': 'Yemen',
        'tel': '967'
    }, {
        'short': 'YU',
        'name': i18n.t('南斯拉夫'),
        'en': 'Yugoslavia',
        'tel': '381'
    }, {
        'short': 'ZA',
        'name': i18n.t('南非'),
        'en': 'SouthAfrica',
        'tel': '27'
    }, {
        'short': 'ZM',
        'name': i18n.t('赞比亚'),
        'en': 'Zambia',
        'tel': '260'
    }, {
        'short': 'ZR',
        'name': i18n.t('扎伊尔'),
        'en': 'Zaire',
        'tel': '243'
    }, {
        'short': 'ZW',
        'name': i18n.t('津巴布韦'),
        'en': 'Zimbabwe',
        'tel': '263'
    }
]

export default phoneAreaCode
