锘?""Code Agent 鈥?浠ｇ爜缂栧啓/淇/Bug鍒嗘瀽/娴嬭瘯"""
import os
import re
from datetime import datetime

class CodeAgent:
    """浠ｇ爜Agent 鈥?璇讳唬鐮併€佸啓浠ｇ爜銆佷慨Bug銆佺敓鎴愭帴鍙?""

    @staticmethod
    async def analyze_file(filepath: str) -> dict:
        """鍒嗘瀽鍗曚釜浠ｇ爜鏂囦欢"""
        if not os.path.exists(filepath):
            return {"error": f"鏂囦欢涓嶅瓨鍦? {filepath}"}
        with open(filepath, "r", encoding="utf-8") as f:
            content = f.read()
        ext = os.path.splitext(filepath)[1]
        lines = content.count("\n") + 1
        return {
            "file": filepath,
            "language": _lang_from_ext(ext),
            "lines": lines,
            "size_kb": round(len(content) / 1024, 1),
            "functions": _extract_functions(content, ext),
            "imports": _extract_imports(content, ext),
        }

    @staticmethod
    async def search_code(directory: str, pattern: str) -> list:
        """鎼滅储浠ｇ爜搴?""
        results = []
        for root, dirs, files in os.walk(directory):
            dirs[:] = [d for d in dirs if d not in ("node_modules", ".git", "__pycache__", "dist")]
            for fname in files:
                if fname.endswith((".py", ".js", ".vue", ".java", ".sql")):
                    fpath = os.path.join(root, fname)
                    try:
                        with open(fpath, "r", encoding="utf-8", errors="ignore") as f:
                            for i, line in enumerate(f, 1):
                                if pattern.lower() in line.lower():
                                    results.append({
                                        "file": fpath,
                                        "line": i,
                                        "content": line.strip()[:200],
                                    })
                    except Exception:
                        pass
        return results[:50]

    @staticmethod
    async def generate_api(name: str, fields: list) -> str:
        """鐢熸垚FastAPI鎺ュ彛浠ｇ爜"""
        code = f'''"""Auto-generated by Friday Code Agent"""
from fastapi import APIRouter, Depends
from pydantic import BaseModel
from auth import verify_token

router = APIRouter(prefix="/{name.lower()}", tags=["{name}"])

class {name}Request(BaseModel):
'''
        for field in fields:
            code += f"    {field['name']}: {field.get('type', 'str')}\n"

        code += f'''
@router.post("/")
async def create_{name.lower()}(req: {name}Request, _=Depends(verify_token)):
    """鍒涘缓{name}"""
    return {{"ok": True, "data": req.dict()}}

@router.get("/")
async def list_{name.lower()}(_=Depends(verify_token)):
    """{name}鍒楄〃"""
    return {{"ok": True, "items": []}}
'''
        return code

def _lang_from_ext(ext: str) -> str:
    return {".py": "Python", ".js": "JavaScript", ".vue": "Vue", ".java": "Java", ".sql": "SQL"}.get(ext, ext)

def _extract_functions(content: str, ext: str) -> list:
    if ext == ".py":
        return re.findall(r"def (\w+)", content)[:20]
    elif ext in (".js", ".vue"):
        return re.findall(r"(?:function|const|let|async)\s+(\w+)", content)[:20]
    return []

def _extract_imports(content: str, ext: str) -> list:
    if ext == ".py":
        return re.findall(r"(?:from|import)\s+(\S+)", content)[:20]
    return []
