-- V5 Window1: 价格字段 DOUBLE → DECIMAL(18,6)
-- 执行: docker exec -i mall-db mysql -uroot -p malldb < sql/V5_window1_price_decimal.sql

ALTER TABLE T_MALL_ORDERS_GOODS
  MODIFY COLUMN GOODS_PRIZE DECIMAL(18,6) COMMENT '商品价格',
  MODIFY COLUMN GOODS_REAL DECIMAL(18,6) COMMENT '实际价格',
  MODIFY COLUMN SYSTEM_PRICE DECIMAL(18,6) COMMENT '系统价格',
  MODIFY COLUMN FEES DECIMAL(18,6) COMMENT '手续费',
  MODIFY COLUMN TAX DECIMAL(18,6) COMMENT '税费';
