-- V5 mall_states table for 3-level address cascading (Country → State → City)
-- 2026-05-24

CREATE TABLE IF NOT EXISTS mall_states (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    STATE_NAME_EN VARCHAR(255) NOT NULL,
    STATE_NAME_TW VARCHAR(255) NOT NULL DEFAULT '',
    STATE_NAME_CN VARCHAR(255) NOT NULL DEFAULT '',
    COUNTRY_ID BIGINT NOT NULL,
    CREATED_AT TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FLAG TINYINT(1) NOT NULL DEFAULT 1,
    INDEX idx_country_id (COUNTRY_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='省/州表';
